INSERT INTO Tag (tag_name) VALUES 
	("knife"),
	("skillet"),
	("oven"),
	("microwave"),
	("baking dish"),
	("saucepan"),
	("mixer"),
	("sheet pan"),
	("large pot"),
	("medium pot"),
	("small pot"),
    ("wok"),
    ("Stove"),
    ("Waffle iron"),
    ("Toaster oven"),
    ("Toaster"),
    ("Sous-vide cooker"),
    ("Rice cooker"),
    ("Popcorn maker"),
    ("Pressure cooker"),
    ("Instant Pot"),
    ("Espresso machine"),
    ("Deep fryer"),
    ("steamer"),
    ("Air fryer"),
    ("Butane torch"),
    ("Barbecue grill"),
    ("teapot"),
    ("electric kettle"),
    ("cheese grater"),
    ("paring knife"),
    ("butcher knife"),
    ("peeler"),
    ("wine opener"),
    ("basket steamer"),
    ("collander"),
    ("mug"),
    ("mixing bowl"),
	("cutting board"),
    ("blender"),
    ("aluminum foil"),
    ("baking sheet"),
    ("muffin tin"),
    ("bundt pan"),
    ("casserole dish"),
    ("mandoline"),
    ("measuring cups"),
    ("digital scale"),
    ("thermometer"),
    ("potato masher"),
    ("pizza cutter"),
    ("scissors"),
    ("whist"),
    ("spatula"),
    ("stand mixer"),
    ("pasta roller"),
    ("twine"),
    ("can opener"),
    ("ice cream scoop"),
    ("slotted spoon"),
    ("sieve"),
    ("rolling pin"),
    ("potato ricer"),
    ("spiralizer"),
    ("ladle");
    
