

INSERT INTO Recipe 
(recipe_id, 
title,
description,
minutes, 
servings, 
instructions, 
user_id) VALUES
(44,
"Black-Eyed Pea Soup",
"This Instant Pot Black Eyed Pea Soup is an easy way to cook this hearty, cheap, and nutritious soup with dried black eyed peas in half the usual time! And it’s a great way to use up any leftover ham (or a ham bone) you have from the holidays. In the south, it’s traditional to eat black eyed peas and greens on New Year’s Day for good health, prosperity, and luck in the new year. ",
180,
3.0,
"Sort through the peas and pick out any pebbles or other debris. Rinse the peas under cold water. Put the peas in a 5-quart Dutch oven and cover with 5 cups cold water. Place over high heat and bring to a boil; boil for 1 minute. Remove from the heat, cover and let peas soak for 1 hour. Cook the bacon in a large skillet over medium heat until crispy, 6 to 8 minutes. Transfer the bacon to a paper towel-lined plate to cool. When cool, crumble the bacon and set aside. Add the oil to the skillet with the bacon fat Add the onions, carrots and celery and cook, stirring frequently, until tender, about 10 minutes. Add the collard greens and garlic and cook until the garlic is fragrant, about 1 minute. Add the vegetables to the Dutch oven along with the chicken broth, ham hock, crumbled bacon, rice and 4 cups water. Bring the mixture to a boil over medium-high heat. Reduce the heat to a simmer and cook, covered, until the peas and rice are tender, 45 minutes to 1 hour. Remove the ham hock from the Dutch oven. Discard the skin and bone. Chop the meat into small pieces and return it to the Dutch oven. Season the soup with salt and pepper.",
55),

(1,
"Spaghetti Cacio e Pepe",
"Cacio e Pepe is a beloved Roman dish made with things you can easily find in your pantry, but there are as many ways to make it as there are cooks in Italy. In this version, olive oil adds a little grassiness and Parmigiano-Reggiano, in addition to the classic Pecorino-Romano, is used to round out the flavors and add an umami richness. If you don't have Parmigiano in the house, simply make the dish with all Pecorino and lower the salt in your pasta water by a tablespoon.",
25,
4.0,
"Bring 6 quarts of water to a boil in a large pot over high heat and add 4 tablespoons salt. Drop the pasta into the water. After 1 minute, when the pasta begins to soften, stir to prevent the pasta from sticking together and to submerge it completely in the water. Cook according to the package directions for al dente, stirring occasionally. When the pasta is ready, remove 2 cups of pasta water and set aside. Drain the pasta through a colander.  Heat the oil in a large skillet over medium heat, then add 2 tablespoons black pepper and cook until the peppercorns begin to warm and become fragrant, about 30 seconds. Stir in 1/2 cup of the pasta water and then the pasta and stir. Pull the pot off the heat and add the Pecorino and Parmigiano, stirring and tossing vigorously until they melt and the sauce becomes creamy. If the mixture becomes dry, clumpy or stuck together, add more pasta water, 1/4-cup at a time, stirring and tossing until a creamy consistency is reached. (The pasta will thicken as it stands.) Add a little more pasta water at a time to loosen it back up again, if you like. (You might not use all of the pasta water.)  Serve immediately sprinkled with more Pecorino-Romano and black pepper.",
5),

(2,
"Chocolate-Pretzel Cereal Treats",
"Use chocolate cereal for these marshmallow-bound treats and stir in crushed pretzels. Drizzle with chocolate and chill before serving.",
65,
24.0,
"Line a 9-by-13-inch baking dish with aluminum foil leaving a 2-inch overhang on the two short ends. Lightly coat the foil with butter. Melt the butter in a large pot set over medium heat. Add the marshmallows and cook, stirring occasionally, until the marshmallows melt, about 5 minutes. Remove from the heat and stir in the vanilla and a pinch of salt and then the cereal and pretzels until well mixed. Transfer to the prepared baking dish and press into an even layer. Set aside at room temperature until cooled and firm, about 30 minutes. Melt the chocolate and coconut oil together in a small microwave safe bowl for 30-second increments in the microwave, stirring, until smooth. Drizzle over the bars, cover and refrigerate until the chocolate hardens, about 15 minutes. Cut into bars.",
38),

(3,
"Senate Bean Soup",
"A delicious bean soup for the cold winter months!",
125,
8.0,
"Put the beans in a large bowl and cover with about 3 times their volume of cold water. Soak overnight in a cool place. Drain the beans and transfer to a large pot or Dutch oven. Add 10 cups water and the ham. Bring to a simmer over medium heat, then reduce the heat to low and cook until the beans are tender, about 1 hour, 30 minutes. Transfer the ham to a plate to cool slightly, then remove the bone, if used, and dice the meat. Return the meat to the pot. Meanwhile, cover the potato with water in a saucepan and season with salt. Bring to a boil over medium-high heat, then reduce the heat and simmer until the potato is fork-tender, 20 to 25 minutes. Drain the potato; transfer to a bowl with the milk and mash with a potato masher or fork until smooth. Add the mashed potato to the bean soup and stir until combined. Melt the butter in a large skillet over medium heat. Add the onion, celery, garlic and parsley and cook until the vegetables are translucent, 7 to 10 minutes. Add the vegetable mixture to the soup, reduce the heat to low and cook 1 hour, adding up to 2 more cups water if the soup is too thick. Season with salt and pepper.",
42),

(4,
"Puttanesca with Angel Hair Pasta",
"Quick, easy pasta dish :)",
30,
4.0,
"Bring a pot of salted water to a boil. Cook the pasta according to the package directions for al dente. Drain, toss with some oil and keep warm. Drain the tomatoes into a large bowl and reserve the juice. Roughly crush the tomatoes with your hands. Heat 2 tablespoons of the oil in a large skillet over medium-low heat. Add the garlic, anchovies and chile flakes and cook, stirring occasionally, until the garlic is lightly golden, about 3 minutes. Add the crushed tomatoes and a generous pinch each of salt and pepper. Increase the heat to medium-high and bring to a simmer. Cook, stirring occasionally, until the tomatoes are soft and begin to lose their shape, 5 to 7 minutes. Stir in the olives, capers and reserved tomato juice. Continue to simmer until the sauce has thickened slightly and the flavors have blended, about 10 minutes more. Add the cooked pasta to the skillet along with the parsley and remaining 1 tablespoon oil and toss well. Season with salt and pepper and serve with Parmesan. Copyright 2016 Television Food Network, G.P. All rights reserved.",
65),

(5,
"Buttermilk Cheddar Corn Cakes",
"This is the best recipe you will ever find for buttermild cheddar corn cakes!",
25,
6.0,
"Whisk together the flour, cornmeal, sugar, baking powder and salt in a mixing bowl. Melt the butter in a large nonstick skillet over medium heat. Set aside to cool slightly while you prepare the wet ingredients. Whisk together the egg and buttermilk in a large mixing bowl. While whisking, pour in the melted butter and stir until combined. Stir in the dry ingredients just until combined. (Be sure not to overwork the batter.) Fold in the Cheddar, corn, if using, and chives. Place the skillet over medium heat and add enough butter to coat the bottom. Ladle about 1/2 cup batter into the pan, spreading gently to form a thick circle. Cook until bubbles appear on the surface, 1 to 2 minutes. Flip over and cook until golden brown, about 1 to 2 minutes more. Melt a small pat of butter in the skillet in between each batch (this will help the corn cakes rise). Serve immediately, with more butter and maple syrup, if desired.",
97),

(6,
"Rockin' Rice Pudding",
"",
30,
4.0,
"Combine cooked rice, milk, sugar and butter in a medium saucepan. Add raisins and vanilla. Cook for 25 minutes until most of the liquid is absorbed. Mix in lemon zest and 1/2 teaspoon of cinnamon. Spoon pudding into a serving dish and dust with remaining cinnamon. May serve chilled or at room temperature.",
66),

(7,
"Spinach Tortellini Soup",
"You can make this on a weeknight and have dinner for the next 3 nights. I love this recipe so much.",
15,
4.0,
"Bring the stock to a simmer in a large pot over medium heat. Stir in the tortellini and simmer gently for 3 minutes. Stir in the spinach, garlic, tomatoes and dried basil. Season with salt and pepper. Return to a simmer and cook for 2 to 3 more minutes. Serve hot with the grated Parmesan cheese.",
75),

(8,
"Chocolate-Hazelnut Paninis",
"Toast these challah sandwiches with chocolate-hazelnut spread for a treat you can't wait to get your hands on.",
30,
4.0,
"Divide the chocolate-hazelnut spread evenly among 4 slices of the bread and spread to cover. Sprinkle with the chopped hazelnuts. Top with the remaining slices of bread to make 4 sandwiches. Heat a medium skillet over medium-low heat and melt about half the butter. Working in batches, cook the sandwiches, pressing down lightly as they cook until the bread toasts, about 3 minutes. Turn and toast the other side, adding butter as needed. Dust the sandwiches with confectioners' sugar and serve.",
43),

(9,
"Pasta With Escarole and Chickpeas",
"Super easy, and chickpeas are great.",
25,
4.0,
"Bring a large pot of salted water to a boil. Meanwhile, heat 3 tablespoons olive oil in a large skillet over medium-high heat. Add the garlic and cook 30 seconds, then stir in the escarole, chickpeas, 1/4 teaspoon salt and the red pepper flakes; cover and cook until the escarole wilts, 3 to 4 minutes. Add the pasta to the boiling water and cook as the label directs. After a few minutes, remove 1 1/2 cups of the pasta cooking water and add to the skillet with the escarole mixture; simmer, uncovered, until the liquid is reduced by half and the escarole is tender, about 5 minutes. When the pasta is done, reserve 1 cup cooking water, then drain. Add the pasta to the skillet and cook, tossing to combine, 1 minute; add some of the reserved cooking water if the pasta seems dry. Add the remaining 1 tablespoon olive oil and toss. Remove from the heat and stir in the cheese.",
6),

(10,
"Creamy Tomato Soup",
"",
65,
4.0,
"Heat the butter in a large soup pot over medium-high heat. Add the bacon and cook, stirring, until crisp and most of the fat has rendered, about 1 minute. Using a slotted spoon, transfer the bacon to a paper towel-lined plate and set aside. Lower the heat to medium, add the onion, carrots, celery, and garlic and cook, covered, stirring occasionally, until soft and fragrant, about 8 minutes. Stir in the flour and cook, stirring, for 3 minutes. Pour in the broth and crush the tomatoes through your fingers into the pan. Bring to a boil while whisking constantly. Tie the parsley sprigs, thyme, and bay leaf together with a piece of kitchen twine and add to the pot. Lower the heat and simmer for 20 minutes. Remove from the heat and let cool. Remove and discard the herb bundle. Working in batches, transfer the mixture to a blender and puree until smooth. Return the puree to the pot and reheat over medium heat. Whisk in the heavy cream, salt, and pepper, to taste. Divide among warm soup bowls and serve immediately. Copyright (c) 2004 Television Food Network, G.P., All Rights Reserved.",
87),

(11,
"Quinoa and Rice Pilaf",
"Here's how to cook quinoa with rice: Put them in the pot together and let them simmer until tender. It's really as simple as that! Use the fluffy grains as a side dish or base for a grain bowl. Or try our favorite way to enjoy them -- sprinkled into a salad for a hearty lunch.",
35,
4.0,
"Place the quinoa and rice in a fine-mesh strainer and rinse until the water runs clear. Melt the butter in a medium saucepan over medium-high heat until foamy. Add the quinoa and rice and cook, stirring to coat with the butter, then add the broth or water. Increase the heat to high and bring to a boil, then immediately reduce the heat to low and cover with a tight-fitting lid. Cook for 18 minutes, then remove from the heat and let sit, covered, for 5 minutes. Fluff with a fork and season to taste.",
11),

(12,
"Applesauce Waffles",
"These Belgian-style waffles are crispy on the outside, but the applesauce keeps them moist and almost muffin-like on the inside. Even better, you can make them when you are out of milk and eggs.",
25,
8.0,
"Preheat the waffle iron. Preheat the oven to 200 degrees F if you plan on holding the cooked waffles in the oven. Whisk the flour, baking powder, baking soda and salt together in a medium bowl. Whisk the evaporated milk, applesauce, brown sugar, oil, vanilla and 3/4 cup water in a large bowl. Fold the dry ingredients into the wet, and stir until combined. (Don't mix too much-some lumps are OK-just make sure the flour is coated.) Allow the batter to rest at room temperature for 5 minutes before baking. Ladle enough batter into the waffle iron to fill it to the edges, and cook until crispy and brown, 6 to 7 minutes. (You can tell the waffles are ready when very little steam comes out of the waffle iron.) Continue in batches until all the batter is used. Keep the cooked waffles warm in the oven or covered with foil on a plate while you make the remaining waffles. Sprinkle with powdered sugar and cinnamon, and serve with maple syrup.",
37),

(13,
"Monster Cookie Dough",
"",
25,
1.0,
"Put the flour in a microwave-safe bowl and microwave on high until the flour reaches a temperature of 180 degrees F, 1 to 1 1/2 minutes. Whisk to get rid of as many lumps as you can. Set it aside to cool. In a stand mixer fitted with a paddle attachment, combine the peanut butter, brown sugar, sugar, butter, heavy cream, vanilla and salt and mix on medium-high, scraping down the sides of the bowl periodically with a rubber spatula to ensure that everything gets combined, until light and fluffy, 3 to 4 minutes. Add the flour and oats and mix to combine. Add the M&M's and mix to combine. Store by the scoop or in balls in the fridge in an airtight container for up to a week.  ",
54),

(14,
"Penne a la Carbonara",
"",
35,
4.0,
"Heat a large saute pan, until hot. Add pancetta and saute until golden brown and crispy, about 5 minutes. Season with black pepper and remove pan from heat. In a medium bowl, beat the eggs and cream. Season with salt and pepper. Stir in Parmesan, reserving 2 tablespoons for garnish. In a large pot, boil 6 quarts of salted boiling water. Add pasta and cook until al dente, about 8 to 10 minutes. Drain pasta in a colander. Do not rinse with water; you want to retain the pasta's natural starches so that the sauce will stick. While the pasta is still hot, return it back to the pot. Add the browned pancetta and mix well. Add the cream mixture and coat the pasta completely. It's important to work quickly while the pasta is still warm so that the cream mixture will cook, but not curdle. Add remaining Parmesan and chopped parsley.",
81),

(15,
"Skillet Hash and Eggs",
"",
40,
4.0,
"Preheat the oven to 400 degrees F. Pierce the potatoes in a few places with a fork and microwave until almost tender, about 10 minutes, turning halfway through. Let cool slightly, then peel and cut into 1/2-inch dice. Heat the butter in a large cast-iron skillet over medium-high heat. Add the kielbasa and cook, stirring, until it starts to brown, about 3 minutes. Add the onion and caraway seeds and cook until the onion is soft, about 3 minutes. Stir in the potatoes, then flatten the hash into an even layer, pressing gently with a spatula. Cook undisturbed until crunchy and browned on the bottom, about 5 minutes. Flip the hash in sections and cook until browned on the other side, about 5 more minutes. Remove from the heat. Using a spoon, make 4 shallow indentations in the hash and crack 2 eggs into each. Transfer to the oven and bake until the egg whites set, about 10 minutes. Season with salt and pepper and top with the parsley and scallions.",
15),

(16,
"Instant Pot Frozen Chicken Teriyaki with Rice and Broccoli",
"You really can cook a whole frozen chicken breast in the Instant Pot® without thawing it first! This is a one-pot meal that comes together with little preparation and is ideal for busy weeknights. Be sure to rinse the rice until the water runs clear to ensure that it does not stick to the bottom of the pot while it cooks. The perfect cook time for the chicken breast depends on its size but is easy to remember: Plan on 6 minutes for a 6-ounce breast and add 1 minute for every extra ounce beyond that.",
45,
4.0,
"Add 1 1/4 cups water and the rice to a 6- or 8-quart Instant Pot®. Place the broccoli on top of the rice. Follow the manufacturer’s guide for locking the lid and preparing to cook. Set to pressure cook on high for 5 minutes (see Cook's Note). After the pressure-cook cycle is complete, follow the manufacturer’s guide for natural release. After 10 minutes, being careful of any remaining steam, unlock and remove the lid. Gently scoop out the broccoli and rice into a medium bowl, cover with plastic wrap and set aside until ready to serve.   Add the oil, garlic, scallion whites and ginger to the same pot (there is no need to rinse the pot out). Set to high saute for 4 minutes and cook until softened, stirring frequently with a wooden spoon. Add the broth, soy sauce, brown sugar, honey, salt and black pepper, scraping the browned bits from the bottom of the pot with a wooden spoon.   Add the chicken breasts. Follow the manufacturer’s guide for locking the lid and preparing to cook. Set to pressure cook on high for 6 minutes (for a 6-ounce chicken breast) to 8 minutes (for an 8-ounce breast). After the pressure-cook cycle is complete, follow the manufacturer’s guide for natural release. After 10 minutes, being careful of any remaining steam, unlock and remove the lid. Transfer the chicken to a cutting board using tongs and slice crosswise.  In a small bowl, combine the cornstarch with 2 teaspoons cold water and add to the sauce in the pot. Set to high saute for 4 minutes. Continuously whisk until the teriyaki sauce is thickened.   Drizzle the sauce over the sliced chicken and serve with the cooked rice and broccoli. ",
12),

(17,
"Pantry Pasta with Romesco Sauce",
"Romesco is a Spanish sauce made with bread (as a thickener) and roasted peppers and nuts. This version twists those components into a kind of pesto that is wonderfully smoky and tangy. We've made it with roasted almonds and smoked paprika, but you can also try it with smoked almonds and regular Spanish paprika.",
30,
6.0,
"Bring a large pot of salted water to a boil. Add the pasta and cook according to the package directions, until al dente. Reserve 1 cup of pasta cooking water, then drain the pasta. Meanwhile, combine the red peppers, whole almonds, breadcrumbs, vinegar, granulated garlic and paprika in a food processor and process until the texture is coarse but uniform. With the motor running, slowly pour in the oil and process until the sauce is thickened and emulsified. Season with 1/2 teaspoon salt and 1/4 teaspoon black pepper. Transfer the sauce to a large bowl. Add the pasta and enough of the reserved pasta water so that the sauce is loose enough to pour but smooth enough to stick to the pasta. Divide the pasta among individual bowls, and sprinkle with the chopped almonds.",
18),

(18,
"Chickpea Curry with Rice",
"",
35,
4.0,
"Cook the basmati rice according to the package instructions. Heat the oil in a medium skillet over medium-low heat. Add the onions, season with salt and pepper and cook until the onions are dark brown and caramelized, about 10 minutes. Stir in the curry powder and garlic and cook for 30 seconds. Pour in the vegetable stock and stir to scrape up all the brown bits in the pan. Add the chickpeas, coconut milk, honey and a squirt of sriracha. Bring to a boil, reduce the heat and simmer for 10 minutes. Taste and adjust the seasoning. Warm the naan in the microwave. Serve the curry over the rice with the warmed naan. Garnish with the cilantro.",
12),

(19,
"Spaghetti with Oil and Garlic (Aglio e Olio)",
"",
26,
4.0,
"Bring a large pot of cold water to a boil over high heat, then salt it generously. Add the pasta and cook, stirring occasionally until al dente, tender but not mushy, about 8 minutes. While the pasta cooks, combine the garlic, olive oil, 1 teaspoon salt and the red pepper flakes in a large skillet and warm over low heat, stirring occasionally, until the garlic softens and turns golden, about 8 minutes. Drain the pasta in a colander set in the sink, reserving about a 1/4 cup of the cooking water. Add the pasta and the reserved water to the garlic mixture. Mix well. Add the parsley and lemon zest (if using). Adjust seasoning, to taste. Transfer to a large serving bowl or divide amongst 4 to 6 dishes. Serve topped with grated cheese, if desired.",
62),

(20,
"Quick and Easy Minestrone",
"Traditionally, minestrone is slow-simmered with Parmigiano-Reggiano rinds to impart a rich umami flavor to the broth. In our shortcut version, soy sauce is used instead, adding instant depth to this pantry-friendly soup.",
25,
4.0,
"Heat the oil in a medium pot over medium-high heat. Add the corn and cook, stirring occasionally, until it starts to brown slightly, about 3 minutes. Add the tomato paste, rosemary and oregano and cook, stirring constantly, until the tomato paste begins to darken in color, about 1 minute. Slowly whisk in the chicken broth until the paste is smooth and incorporated into the liquid. Add the whole can of diced tomatoes (including the liquid), and bring the mixture to a boil. Stir in the pasta, the white beans and reserved liquid and the soy sauce. Season with salt and pepper. Cook until the pasta is al dente, 7 to 8 minutes, stirring in the green beans during the last 2 minutes of cooking. Serve in individual bowls with a little oil drizzled on top.",
25),

(21,
"Lentil Sloppy Joes",
"",
60,
6.0,
"Heat 1 tablespoon vegetable oil in a medium saucepan over medium-high heat. Add the onion, carrot, bell pepper and 2 tablespoons ketchup and cook, stirring occasionally, until the vegetables are slightly soft, about 3 minutes. Add the garlic and cook, stirring, 30 seconds. Add the lentils, oregano and 4 cups water; bring to a boil and cook 5 minutes, then reduce the heat to medium low and simmer until the lentils are tender and the water is absorbed, 35 to 40 minutes (add up to 1 more cup water if necessary). Season with salt and pepper.  Heat the remaining 1 tablespoon vegetable oil in a large nonstick skillet over medium-high heat. Add the beef and cook, breaking it up with a spoon, until it begins to brown, about 2 minutes. Add the Worcestershire sauce and the remaining 6 tablespoons ketchup and cook, stirring, until combined. Add the lentil mixture and 1 cup water and cook, stirring occasionally, until the lentils are soft and the mixture thickens, about 8 minutes. Season with salt and pepper.  Fill the buns with the cheese and lentil mixture. Top with pickles and/or pickled jalapenos. ",
41),

(22,
"Cold Curry-Peanut Noodles",
"",
35,
4.0,
"Bring a large pot of salted water to a boil. Add the spaghetti and cook as the label directs. Reserve about 1/2 cup cooking water, then drain in a colander and rinse under cold water. Shake off the excess water. Meanwhile, puree the peanut butter, curry paste, vinegar, lime juice, cilantro, 1/2 cup water and 1 teaspoon salt in a food processor or blender until smooth. Toss the spaghetti with the peanut sauce, scallions, cucumber and carrot in a large bowl until coated. Season with salt and stir in some of the reserved cooking water to loosen the sauce, if necessary. Transfer to bowls and top with more cilantro and pepper flakes, if desired. Serve with lime wedges. ",
77),

(23,
"Spicy Three-Bean Pantry Chili",
"This vegetarian chili gets its rich flavor from caramelizing tomato paste and warming herbs, rather than long hours of cooking. You can amp up the heat by using a spicy salsa or some of the adobo paste (though the chile itself is pretty hot). Add corn for some sweetness, or canned hominy for a chunkier and funkier chili.",
40,
6.0,
"Heat the oil in a medium pot over medium-high heat. Add the tomato paste and cook, smearing and stirring constantly with a heat-proof spatula or flat-edged wooden spoon, until dark and aromatic, about 90 seconds. Add the chipotle, chili powder and oregano, and cook, stirring, for 1 minute. Stir in the salsa and 1 1/4 cup water. Stir in the beans and hominy. Bring to a boil, reduce the heat to medium-low, cover and simmer for 25 minutes, stirring occasionally. Meanwhile, bring 1 1/2 cups water to a boil in a small saucepan with a lid. Stir in the rice, reduce the heat to medium low, cover and simmer until the water is absorbed, about 15 minutes. Remove from the heat and let stand, covered, 5 minutes. Remove the chili from the heat, stir in the cider vinegar and let stand 1 minute. Fluff the rice with a fork, divide it among 6 serving bowls and top with the chili. Serve with pickled jalapenos and tortilla chips, if desired.",
72),

(24,
"S'mores Bark",
"We've combined all the elements of a s'more into this delicious bark. It's got crunch from the graham crackers, richness from the chocolate and fire-roasted flavor from broiling the marshmallows-easier than toasting them over a campfire (though admittedly not as much fun).",
60,
1.0,
"Line a baking sheet with parchment. Heat the chocolate in a medium microwave-safe bowl in the microwave at 75 percent power until soft, about 2 minutes. Stir the chocolate and microwave again until melted, up to 2 minutes more. (Alternatively, put the chocolate in a heatproof bowl. Bring a saucepan filled with an inch or so of water to a very slow simmer; set the bowl over, but not touching, the water, and stir occasionally until melted and smooth.) Position the oven rack 3 inches below the heating element of the broiler and preheat the oven to broil. Place the marshmallows on a rimmed baking sheet so they are not overlapping, and broil until the tops just begin to toast, about 10 seconds, turning the pan for even browning. (Alternatively, you can use a kitchen torch to char the marshmallows.) Allow to cool at room temperature for 10 minutes. Fold half the marshmallows and graham crackers into the chocolate, and stir to coat. (Some of the marshmallows may melt, but that's OK.) Pour the chocolate onto the prepared baking sheet, and spread evenly with an offset spatula into an 8 1/2-by-11 inch rectangle. Poke the rest of the marshmallows and the graham cracker pieces into the chocolate in a random yet attractive pattern. (This part may be messy, but stretching the marshmallows into the bark will look cool.) Lightly press down the toppings. Allow the bark to set in the refrigerator for 1 hour. Break into pieces to serve.",
21),

(25,
"The Best Tuna Salad",
"While we love many kinds of tuna salad, this classic version tops them all. The crispy celery and red onion give add zest and crunch, while mayonnaise and touch of mustard marry it all together. The lemon juice is optional as it’s not traditional, but we strongly recommend it to brighten up the flavors of the final dish.",
15,
3.0,
"In a small mixing bowl break up the tuna with a fork. Toss with the celery, onion and parsley. Add the mayonnaise, mustard and season with pepper, to taste. Stir to combine. Add lemon juice, to taste, if using. ",
5),

(26,
"Garlic Ramen Popcorn",
"",
15,
8.0,
"Add the popcorn and scallions to large bowl. Combine the butter, ramen seasoning and garlic in a small saucepan over low heat. Cook until the butter is melted and the garlic is golden but not brown. Pour over the popcorn and toss well.",
4),

(27,
"Pantry Pasta",
"",
30,
2.0,
"Add the onions into a skillet with the olive oil over medium heat. Saute for a few minutes, and then add in the diced tomatoes, chicken stock, olives, artichoke hearts and garlic. Season with a pinch of salt and pepper. Stir and simmer over low heat for 15 minutes, stirring occasionally.  Add the cooked pasta to the skillet and stir to combine with the sauce. Mix in the pesto. Toss in the feta and top with the pine nuts.",
78),

(28,
"Spinach with Tahini Sauce",
"",
15,
4.0,
"Mix 1 tablespoon tahini, 2 teaspoons low-sodium soy sauce and 1 teaspoon each rice vinegar, sugar and water until smooth. Cook 1 pound spinach (not baby) in salted water until tender, 1 to 2 minutes. Plunge into a bowl of ice water, drain and squeeze dry. Toss with 1 teaspoon sesame oil and season with salt. Drizzle with the tahini sauce and toasted sesame seeds.",
61),

(29,
"Polenta with Roasted Tomatoes",
"",
40,
4.0,
"Position a rack in the upper third of the oven and preheat to 450. Toss the tomatoes, olive oil and 1/4 teaspoon salt in a large ovenproof skillet. Roast in the oven until the tomatoes are charred around the edges, about 25 minutes. Reduce the oven temperature to 300 but keep the tomatoes inside. Meanwhile, bring 5 cups water to a boil in a saucepan over medium heat. Slowly whisk in the polenta until smooth and creamy. Add 1 teaspoon salt, and pepper to taste. Remove from the heat, cover and keep warm. Bring a pot of salted water to a boil. Slice the chard leaves into wide strips and the stems into 1-inch pieces. Boil the stems until almost tender, about 5 minutes, then add the leaves and cook until both are tender, about 3 more minutes. Drain the chard. Remove the skillet from the oven and place over medium-high heat. Push the tomatoes to one side, add the butter and swirl until the butter is golden brown. Add the chard and toss to coat. Divide the polenta among 4 bowls. Top with the tomatoes and chard. Season the cheese with salt and sprinkle over the top.",
89),

(30,
"Black Bean Hummus",
"",
25,
4.0,
"Blend all the ingredients, except the lettuce, in a food processor until almost smooth. Let sit for 15 minutes before serving with iceberg lettuce wedges.",
12),

(31,
"Agnolotti With Artichoke Sauce",
"",
25,
4.0,
"Combine the artichokes, half-and-half, garlic, red pepper flakes and 1/4 teaspoon salt in a large skillet and bring to a simmer over medium heat. Cover and cook until the artichokes are tender, about 5 minutes. Add the peas and continue to cook, covered, until tender, about 5 more minutes. Remove from the heat and stir in the lemon zest and juice. Discard the garlic clove. Meanwhile, bring a large pot of salted water to a boil. Add the agnolotti and cook as the label directs. Reserve 1/2 cup cooking water, then drain the pasta and transfer to the skillet with the sauce. Add the parmesan to the skillet and gently stir until the pasta is coated. Thin the sauce with some of the reserved cooking water. Stir in the basil.",
23),

(32,
"Peanut Butter Ramen",
"",
20,
4.0,
"In a large stockpot set over medium-high heat, cook the ramen according to the package directions, then drain and set aside. Heat 2 tablespoons of the oil in a high-sided medium skillet over medium heat. Add the veggie medley and then the peanut butter, chili sauce, soy sauce, lime juice, green onion, red pepper flakes and the remaining 2/3 cup olive oil. Cook, whisking, until the peanut butter is melted and the oil is incorporated, 3 to 5 minutes. Add the drained noodles and the chicken, and toss to coat. Cook until heated through, 3 to 5 minutes. Transfer to a large serving dish and serve warm.",
18),

(33,
"Curry Fried Rice",
"",
10,
4.0,
"Heat the oil in a large nonstick skillet over high heat. Add the beaten egg and swirl the pan; let set, then transfer to a plate. Add the scallions to the pan along with the curry powder and pepper to taste; stir-fry 2 minutes. Stir in the cooked rice; spread in an even layer and cook 3 minutes. Add the egg, and salt to taste; stir to break up the egg. Drizzle with the sesame oil.",
40),

(34,
"Power Balls",
"",
60,
30.0,
"In a food processor, pulse the oats, peanut butter, honey, chocolate chips, cranberries, sunflower seeds and flax seeds until fully combined. Cover and refrigerate for 30 minutes. Line a baking sheet with waxed paper. Form balls from the mixture (about 1 1/2 tablespoons each) and place them on the baking sheet. Refrigerate for 30 minutes before serving.",
32),

(35,
"Tomato-Ginger Couscous",
"",
30,
1.0,
"Puree 2 tomatoes, 2 tablespoons each tomato paste and water, 1 tablespoon red wine vinegar, a 2-inch piece of peeled ginger, 1 garlic clove, 3/4 teaspoon kosher salt and 1/4 teaspoon ground turmeric. Heat 2 tablespoons olive oil in a skillet over medium heat; add the puree and cook, stirring, until thickened to a paste, 12 minutes. Add 1 cup water and bring to a simmer. Remove from the heat and stir in 1 cup couscous; cover and let sit 10 minutes. Fluff with a fork, season with salt and top with chopped cilantro.",
46),

(36,
"Rigatoni with Spicy Shrimp",
"",
30,
4.0,
"Bring a large pot of salted water to a boil. Add the pasta and cook as the label directs. Reserve 1 cup cooking water, then drain. Meanwhile, heat the olive oil in a large nonstick skillet over medium-high heat. Add the shrimp in a single layer and season with 1/4 teaspoon red pepper flakes and a pinch of salt. Cook until just pink, about 2 minutes, then flip and cook until no longer translucent,1 to 2 more minutes. Transfer to a plate. Add the shallot to the skillet and cook, stirring with a wooden spoon, until translucent, about 2 minutes. Add the wine and cook, scraping up any browned bits, until slightly reduced, about 1 minute. Add the tomatoes, half of the basil, the remaining 1/4 teaspoon red pepper flakes and 1/4 teaspoon salt; cook until slightly thickened, about 5 minutes. Stir in the heavy cream and cook 1 more minute. Return the shrimp and any collected juices to the skillet. Stir in the pasta; add enough of the reserved pasta cooking water to loosen the sauce. Season with salt. Top with the remaining basil.",
10),

(37,
"Vegan Pancakes",
"You don't need eggs and dairy for super-fluffy pancakes-the extra baking powder in this recipe helps with that. We love the flavor and tenderness that coconut oil gives these easy-to-make pancakes.",
45,
6.0,
"Preheat the oven to 250 degrees F. Whisk together the flour, sugar, baking powder and 1 teaspoon salt in a medium bowl. Whisk together the soy milk, coconut oil and vanilla in a second medium bowl (don't worry if the coconut oil clumps). Add the soy milk mixture to the flour mixture and gently fold until just combined (it's OK if there are lumps). Heat a nonstick griddle or large nonstick skillet over medium-low heat. Add 1 teaspoon of the vegetable oil. Once the pan is hot, add three 1/4-cup mounds of batter, evenly spaced, and cook until the pancakes begin to bubble and are golden brown, 4 to 5 minutes. Carefully flip the pancakes and cook until the underside is golden brown and the pancakes are cooked through, 3 to 4 minutes (adjust the heat as necessary for consistent browning). Repeat with the remaining vegetable oil and batter. Transfer the cooked pancakes to the oven to keep warm. Serve 2 per person with maple syrup, nut butter, jam or your favorite topping.",
70),

(38,
"Ravioli Alfredo With Peas",
"",
20,
4.0,
"Bring a large pot of salted water to a boil. Add the ravioli and cook as the label directs. Reserve 1/2 cup of the cooking water, then drain the ravioli.   Combine the butter, cream and peas in a large skillet and bring to a simmer over medium heat; cook 1 minute. Add the ravioli, cheese, nutmeg and a splash of the reserved cooking water to the skillet and toss. Add more cooking water to thin the sauce, if needed. Season with salt and pepper. Divide among bowls and top with the parsley. ",
38),

(39,
"7-Can Soup",
"",
25,
6.0,
"Empty the corn, chili, kidney beans, pinto beans, black beans, tomatoes and tomatoes with green chiles, liquid included, into a large pot over high heat. Bring to a boil, reduce the heat and simmer for 10 to 15 minutes to bring all the flavors together. Add salt and pepper as needed. Dice the cheese and stir it into the soup until melted. Serve immediately.",
45),

(40,
"Root Beer Baked Beans",
"",
65,
6.0,
"Preheat the oven to 400 degrees F. Set a medium oven-safe pot over medium heat and add the bacon. Cook, stirring, until most of the fat is rendered and the bacon is crisp, about 8 minutes; remove to paper towels with a slotted spoon to drain. Add the onion, garlic and ginger to the drippings in the pot and cook, stirring occasionally, until soft and golden, about 5 minutes. Add the tomato paste and cook until the color deepens, about 1 more minute. Add the root beer, vinegar, molasses, mustard, red pepper flakes and garam masala to the pot. Stir, then bring to a boil. Add the beans and three-quarters of the bacon and gently stir so the beans don't lose their shape. Reduce the heat to medium low and simmer until slightly thickened, about 15 minutes; season with salt and pepper. Transfer to the oven and bake, uncovered, until thick, about 30 minutes. Let cool slightly, then top with the remaining bacon.",
63),

(41,
"Turkey Chipotle Chili with Pepper Jack Cheese Corn Cake Toppers",
"",
30,
4.0,
"Heat deep skillet or wide pot over medium high heat. Add oil and turkey. Crumble meat as it cooks, 3 minutes. Add the onions and garlic, chili powder, and chipotle. Cook another 5 minutes. Season with salt. Add beer and cook another minute, stirring to loosen any bits from the bottom of the pan. Add the stock, tomatoes, and beans and bring to a bubble. Reduce heat and simmer 10 minutes. Heat a nonstick griddle pan over medium high heat. Mix batter and cheese together. Rub grill with butter, nesting the butter in a paper towel to hold on to it. Ladle the batter to make 3-inch cheese and corn cakes. Cook 3 minutes on each side, until golden. Transfer them to a plate and cover with foil to keep warm. Serve bowls of chili with cheese-corn toppers -- like a spicy, corn topped chili pot pie.",
52),

(42,
"Carbonara Beans",
"Create the pantry side dish of your dreams with a few humble ingredients--eggs, bacon, Parmesan and beans! It’s everything you love about traditional carbonara, but with protein-packed cannellini in place of the pasta.",
20,
4.0,
"Bring a medium pot of salted water to a boil. Add the beans, cover and let cook until the beans are just heated through, about 2 minutes. Turn off the heat and let the beans sit in the hot water while the bacon cooks (you want the beans to be very hot when adding to the egg mixture). Stir the egg yolks and Parmesan in a medium bowl until no lumps remain; set aside. Cook the bacon in a large skillet over medium-high heat, stirring occasionally, until crisp, 7 to 8 minutes. Add the garlic and cook, stirring constantly, until softened and very fragrant, about 1 minute. Pour off all but 2 tablespoons of the rendered bacon fat and return the skillet to the stovetop. Reserve 1 cup of the bean water, drain the beans and then add them to the skillet. Cook, stirring constantly, to coat with the bacon fat, about 1 minute.   Ladle 1/2 cup of the reserved bean water into the egg mixture, whisking constantly so the eggs do not cook but are heated. Pour into the skillet and cook, stirring constantly, until the cheese is melted, the sauce begins to thicken and the beans are evenly coated, about 1 minute (if the beans look dry, add more bean water, 2 tablespoons at a time, until the desired consistency has been reached). Fold in the parsley and season with a generous amount of pepper. Transfer to a serving bowl and sprinkle with more Parmesan and parsley.  ",
74),

(43,
"Any Liquor Pantry Cocktail",
"This recipe is really just a 3-2-1 ratio with almost endless adaptations. Start with a base liquor of your choice. Add something sour -- citrus or another unsweetened, tart juice. You can even add a splash of brine from pickled vegetables or a little vinegar to take the cocktail in the direction of a shrub, which has popped up on drink menus all over because it's so refreshing. Finally, add something sweet -- basic simple syrup or just about any other liquid sweetener you have on hand. Once you are ready to shake it with ice, you can personalize it further by throwing a few herb sprigs or pieces of fruit in the shaker.Finish with a topper of seltzer, prosecco or another fizzy beverage, if you like. The proverbial cherry on top can be any garnish you have on hand -- fruit, pickles, candy, herbs, you name it.Begin with simple combinations -- see our suggestions below -- and then experiment to find the ones you like the most.",
5,
1.0,
"Fill a cocktail shaker with ice. Add the liquor, sour and sweet and flavor enhancers if using and shake well. Strain and pour into a glass over ice. Add a fizzy topper if using. Garnish as desired. Whiskey + Pomegranate juice + Honey (no fizzy topper) Gin + Lime juice + Orange juice + Seltzer topper Vodka + Lemon juice + Maraschino cherry juice from the jar + Sliced strawberries + Prosecco topper + Maraschino cherry garnish Tequila + Lime juice and a splash of pickled jalapeno brine + Triple Sec + Lime and jalapeno garnish (no fizzy topper) Bourbon + Lemon juice + Maple syrup + Lemon wedge garnish (no fizzy topper) Rum + Unsweetened pomegranate juice + Simple syrup + Flavored seltzer topper + Fresh fruit garnish Rum + Lime juice and a splash of white wine vinegar + Simple syrup + Blackberries + Prosecco topper + Gummy candy garnish",
38);