use recipedb;

INSERT INTO Tag (tag_id, tag_name) VALUES 
	(1, "vegetarian"),
	(2, "dinner"),
	(3, "dessert"),
	(4, "gluten-free"),
	(5, "italian"),
	(6, "snack"),
	(7, "keto"),
	(8, "breakfast"),
	(9, "korean"),
	(10, "low-sugar"),
	(11, "indian"),
	(12, "thai"),
	(13, "lunch"),
    (14, "vietnamese"),
	(15, "vegan"),
	(16, "meal prep"),
	(17, "low carb"),
	(18, "mediterranean"),
	(19, "latvian"),
	(20, "japanese"),
	(21, "norwegian"),
	(22, "chinese"),
	(23, "mexican"),
	(24, "cuban"),
	(25, "antioxidants"),
	(26, "kid-friendly"),
	(27, "budget"),
	(28, "party food"),
	(29, "midnight snack"),
    (30, "high-protein"),
	(31, "dairy-free");