use recipedb;
select * from user;
INSERT INTO User 
        (first_name,
        last_name, 
        username, 
        email, 
        password,  
        description,
        university_id) VALUES
("Jeralee","Jouhning","jjouhning1","jjouhning1@people.com.cn","c82ce3RuKPvA","Universal coherent product",1650),
("Vivyan","Coll","vcoll2","vcoll2@themeforest.net","hBNJsRep","Quality-focused web-enabled hub",2222),
("Arlyn","Finnis","afinnis3","afinnis3@devhub.com","eUYluJ","Visionary modular application",2075),
("Louis","Danihel","ldanihel4","ldanihel4@hc360.com","w59lIf","Front-line 24 hour access",729),
("Jourdan","Cutts","jcutts5","jcutts5@facebook.com","RLz5fiS5ZQ","Diverse 4th generation Graphical User Interface",1264),
("Bryanty","Richter","brichter6","brichter6@ed.gov","7IXD8WYCbYS","Reverse-engineered homogeneous database",1023),
("Brett","Berrey","bberrey7","bberrey7@ocn.ne.jp","cOmxcl","Ergonomic content-based standardization",1476),
("Briney","Petrashkov","bpetrashkov8","bpetrashkov8@google.co.uk","5UaBDiH","Operative motivating monitoring",2517),
("Roana","Bointon","rbointon9","rbointon9@goo.gl","YybnlRj","Advanced logistical collaboration",547),
("Deeann","Soutter","dsouttera","dsouttera@tiny.cc","EpxAeEr69u7u","Persevering solution-oriented toolset",582),
("Gun","Symmons","gsymmonsb","gsymmonsb@jimdo.com","mCWzrDR77wbV","Intuitive object-oriented solution",857),
("Rhody","Phython","rphythonc","rphythonc@auda.org.au","VZNQvW6qzl","Innovative 5th generation matrix",115),
("Jayme","Petett","jpetettd","jpetettd@nyu.edu","RoeODzURVFP","Diverse attitude-oriented parallelism",1953),
("Roberta","Astall","rastalle","rastalle@g.co","QPF1m0dmb","Horizontal optimal product",1596),
("Marina","Elford","melfordf","melfordf@1und1.de","NIdgt0fWY","Object-based fault-tolerant projection",332),
("Chan","Bucktrout","cbucktroutg","cbucktroutg@geocities.jp","Q91C7c","Persistent eco-centric knowledge user",1976),
("Edeline","Welland","ewellandh","ewellandh@alexa.com","bMuy7CXT4QAK","Upgradable didactic moderator",1267),
("Emmett","Casaro","ecasaroi","ecasaroi@sun.com","EUUpfOEKKc","Object-based encompassing matrix",2041),
("Elwyn","Haggas","ehaggasj","ehaggasj@prlog.org","n15VguU","Universal multi-state groupware",129),
("Willow","Vondra","wvondrak","wvondrak@uiuc.edu","D6OesfwwQePn","Advanced methodical protocol",1882),
("Nappie","McKibbin","nmckibbinl","nmckibbinl@nih.gov","GFtHm2GrR4Xg","De-engineered leading edge hub",1885),
("Lanna","Kenaway","lkenawaym","lkenawaym@google.com.br","eZcFD95JaW","Managed neutral process improvement",2159),
("Redford","Ollerenshaw","rollerenshawn","rollerenshawn@cdc.gov","BpChQ81Jz","Versatile analyzing challenge",223),
("Kit","Strothers","kstrotherso","kstrotherso@dropbox.com","AhNHzlIxwenp","Cross-group value-added throughput",127),
("Barrett","Sigmund","bsigmundp","bsigmundp@wikimedia.org","cvpXamOq","Mandatory leading edge internet solution",2539),
("Marika","Hyndson","mhyndsonq","mhyndsonq@jiathis.com","B0D9cNz","Visionary optimizing benchmark",1900),
("Janet","Filipic","jfilipicr","jfilipicr@cpanel.net","PyUpRL5","Right-sized contextually-based model",442),
("Talyah","Glide","tglides","tglides@samsung.com","gRaPmPjzxn2x","Enhanced uniform monitoring",144),
("Nelli","Asbery","nasberyt","nasberyt@census.gov","HZUa2foDtC","Compatible interactive approach",721),
("Rois","Sleite","rsleiteu","rsleiteu@google.fr","D1gyClR36j","Optimized modular Graphic Interface",1692),
("Ignacius","Langmaid","ilangmaidv","ilangmaidv@adobe.com","oCnrrlD","Devolved upward-trending throughput",421),
("Kathrine","Lehemann","klehemannw","klehemannw@hibu.com","pvfnduOuTiX","Universal homogeneous extranet",1180),
("Pincas","Neesham","pneeshamx","pneeshamx@nydailynews.com","BHMoChWPKQ","Cloned dedicated model",1981),
("Beltran","Bowmer","bbowmery","bbowmery@hud.gov","f8k83mggyNE","Multi-channelled multi-tasking task-force",2187),
("Town","MacAlaster","tmacalasterz","tmacalasterz@google.it","CH8CpAmHC","Synergistic demand-driven superstructure",2555),
("Mariele","Pomery","mpomery10","mpomery10@amazon.com","5QeB31","De-engineered 5th generation concept",2468),
("Darrel","Clackers","dclackers11","dclackers11@upenn.edu","NxGIfSI4BW","Expanded asynchronous functionalities",1903),
("Dulcea","Mandy","dmandy12","dmandy12@ucla.edu","U03ePQjRvIf","Advanced mission-critical orchestration",2130),
("Diahann","Handes","dhandes13","dhandes13@jigsy.com","n9M6lw","Integrated 24 hour definition",2868),
("Ericha","Kristiansen","ekristiansen14","ekristiansen14@mozilla.com","jGEmzjop","Cloned regional artificial intelligence",2710),
("Huey","Pieper","hpieper15","hpieper15@squidoo.com","ios7IA1T9iIt","Front-line disintermediate system engine",2822),
("Codee","Poker","cpoker16","cpoker16@imgur.com","GMmU7q","Reactive zero tolerance algorithm",275),
("Darren","Caneo","dcaneo17","dcaneo17@columbia.edu","qZ9sXIBvg","Ergonomic heuristic functionalities",2346),
("Anni","Siverns","asiverns18","asiverns18@hostgator.com","zKd834TjWq","Synergistic 5th generation encryption",1789),
("Gamaliel","Maundrell","gmaundrell19","gmaundrell19@tmall.com","JSFpstFttw","De-engineered impactful toolset",2157),
("Ashlan","Petschelt","apetschelt1a","apetschelt1a@walmart.com","6l6sMLXlKQ","Synchronised optimal website",318),
("Eugenius","Jeannot","ejeannot1b","ejeannot1b@timesonline.co.uk","P6Oe4F","Customizable didactic definition",136),
("Robb","Jerwood","rjerwood1c","rjerwood1c@weibo.com","YM6yvVQkGppl","Ameliorated solution-oriented adapter",341),
("Lidia","Linstead","llinstead1d","llinstead1d@blinklist.com","R2zO2xkezzO","Stand-alone discrete website",176),
("Lorant","Genge","lgenge1e","lgenge1e@netvibes.com","tpwxXfup4","Total dynamic productivity",2010),
("Jerrie","Charon","jcharon1f","jcharon1f@ihg.com","qSgaEuGY4f5N","Centralized attitude-oriented pricing structure",1789),
("Jonas","Mishow","jmishow1g","jmishow1g@privacy.gov.au","LGyV4y2OON","Stand-alone leading edge neural-net",810),
("Catherine","Becraft","cbecraft1h","cbecraft1h@ow.ly","vDywzF6ArD3","Mandatory object-oriented core",965),
("Gustie","Elliff","gelliff1i","gelliff1i@blog.com","VCKoO6kUcVRE","Assimilated high-level framework",698),
("Chicky","Renshell","crenshell1j","crenshell1j@google.com.hk","29sKrK","Managed motivating neural-net",2207),
("Stafani","Nutten","snutten1k","snutten1k@home.pl","kkC0P9iqrjV","Enterprise-wide real-time matrix",1411),
("Gregoor","Tyne","gtyne1l","gtyne1l@npr.org","bJLZjZ","Intuitive directional algorithm",214),
("Genny","Slinn","gslinn1m","gslinn1m@simplemachines.org","n6quFYrsf","Business-focused 24/7 system engine",851),
("Cinda","Stubbert","cstubbert1n","cstubbert1n@ibm.com","2InTlYeZL","User-centric 6th generation budgetary management",59),
("Nadean","Boulter","nboulter1o","nboulter1o@oaic.gov.au","8y8LMvn","Grass-roots non-volatile attitude",77),
("Farr","Babinski","fbabinski1p","fbabinski1p@cbslocal.com","89AGWK079","Front-line user-facing help-desk",419),
("Issiah","Pioch","ipioch1q","ipioch1q@de.vu","J9JTmC0Kdw","Adaptive coherent workforce",2129),
("Ermentrude","Benadette","ebenadette1r","ebenadette1r@twitpic.com","kw97Rw5R","Fully-configurable optimizing customer loyalty",1804),
("Dorotea","Beilby","dbeilby1s","dbeilby1s@virginia.edu","gqa1Ob031p","Fundamental exuding project",997),
("Giorgio","Tissell","gtissell1t","gtissell1t@wisc.edu","dZwJaiK1tAK","Public-key fault-tolerant emulation",2610),
("Axe","Albertson","aalbertson1u","aalbertson1u@etsy.com","i8bIBE","Vision-oriented system-worthy firmware",2237),
("Alistair","Ianiello","aianiello1v","aianiello1v@github.com","ZKThgbhv3S","Synergistic 24 hour archive",1998),
("Pearce","Scrauniage","pscrauniage1w","pscrauniage1w@utexas.edu","wjUJ20wVw","Virtual cohesive neural-net",1922),
("Anthony","Posner","aposner1x","aposner1x@disqus.com","YylB67MG","Up-sized real-time matrix",715),
("Brenden","Wooder","bwooder1y","bwooder1y@jigsy.com","W78ZeIL","Organized asymmetric portal",2718),
("Yoshiko","Panton","ypanton1z","ypanton1z@hexun.com","z4MFT2d0h","Public-key motivating artificial intelligence",2160),
("Olivia","Ruter","oruter20","oruter20@ebay.co.uk","eZQgcqbyA7Eg","Sharable hybrid complexity",1866),
("Krystalle","Scotchbrook","kscotchbrook21","kscotchbrook21@furl.net","lBgT4DZ","Synergized web-enabled projection",1373),
("Misti","Bowry","mbowry22","mbowry22@irs.gov","WYLQ9G0pE","Pre-emptive high-level productivity",2597),
("Fayina","Lefwich","flefwich23","flefwich23@github.com","fOO5PT","Open-source bandwidth-monitored knowledge base",1100),
("Ketti","Fulks","kfulks24","kfulks24@joomla.org","1PctPRt","Exclusive 24 hour collaboration",963),
("Rick","Burges","rburges25","rburges25@economist.com","oE6ZfrL","Persevering cohesive circuit",256),
("Esdras","Klimek","eklimek26","eklimek26@businessinsider.com","Ia0oEwF4pTgV","Profit-focused bifurcated utilisation",2005),
("Sabra","Barracks","sbarracks27","sbarracks27@accuweather.com","UWw5hjGTGf","Realigned bandwidth-monitored policy",130),
("Iona","Abberley","iabberley28","iabberley28@yale.edu","bYLHYNu2pX","Multi-channelled value-added middleware",738),
("Colman","Sample","csample29","csample29@dailymotion.com","dSWhgcYeW7","Digitized global initiative",2113),
("Skelly","Diess","sdiess2a","sdiess2a@mlb.com","xopZgY","Enterprise-wide uniform success",1347),
("Lek","Cahill","lcahill2b","lcahill2b@jigsy.com","mMJzYBpGq","Team-oriented user-facing function",2495),
("Ev","Billin","ebillin2c","ebillin2c@statcounter.com","EeMr7qVs3P","Operative clear-thinking time-frame",1152),
("Gwenette","Insull","ginsull2d","ginsull2d@livejournal.com","FLguJPJXl0","Triple-buffered uniform policy",907),
("Con","Guage","cguage2e","cguage2e@sourceforge.net","rIFg0DH6ThL2","Advanced impactful attitude",2773),
("Powell","Kubelka","pkubelka2f","pkubelka2f@sfgate.com","BTm3h3wnwPWd","Ergonomic mobile circuit",411),
("Ulrikaumeko","Fort","ufort2g","ufort2g@youtu.be","xjWyH93IanE","Multi-lateral zero administration help-desk",1189),
("Sena","Butterly","sbutterly2h","sbutterly2h@amazon.co.jp","U1boCQaf6","Distributed interactive system engine",1131),
("Phillie","Lavielle","plavielle2i","plavielle2i@flavors.me","pSloX3v","Quality-focused secondary implementation",1083),
("Rafaelia","Bentham","rbentham2j","rbentham2j@squarespace.com","cYcZqXhY","Cross-group static website",1202),
("Sabina","Bircher","sbircher2k","sbircher2k@discovery.com","p8xRBXKdNVQh","Upgradable interactive access",1261),
("David","Renison","drenison2l","drenison2l@about.me","ner77PXsbeK","Expanded secondary functionalities",579),
("Lynett","Chastey","lchastey2m","lchastey2m@yandex.ru","pCD3PgAP1L","Cloned asynchronous monitoring",289),
("Morris","Taggett","mtaggett2n","mtaggett2n@canalblog.com","NHP3Vco8Q","Open-architected bi-directional utilisation",2016),
("Annecorinne","Clingoe","aclingoe2o","aclingoe2o@tripod.com","MhKVo6","Extended neutral portal",385),
("Sophie","Casino","scasino2p","scasino2p@wiley.com","hfgprH","Integrated object-oriented middleware",112),
("Caspar","Andrivot","candrivot2q","candrivot2q@unc.edu","izmWV7x","Devolved holistic circuit",2749),
("Cornelius","Tumilson","ctumilson2r","ctumilson2r@posterous.com","KxfK4TgN","Pre-emptive 4th generation knowledge base",1492);