INSERT INTO Ingredient (ingredient_name)
('dried black eyed peas')
('thick cut bacon')
('extra virgin olive oil')
('diced onion')
('diced carrots')
('ribs diced celery')
('frozen chopped collard greens')
('garlic')
('low sodium chicken broth')
('smoked ham hock')
('rice blend')
('salt and freshly ground black pepper')
('salt and freshly cracked black pepper')
('spaghetti')
('grated Pecorino Romano')
('grated Parmigiano Reggiano')
('unsalted butter')
('bag mini marshmallows')
('pure vanilla extract')
('salt')
('puffed chocolate cereal')
('crushed pretzels')
('semisweet chocolate')
('coconut oil')
('dried navy beans')
('ham')
('russet potato')
('milk')
('onion')
('celery')
('chopped fresh parsley')
('ground pepper')
('dry angel hair pasta')
('olive oil')
('can  plum tomatoes')
('anchovy fillets')
('crushed red pepper flakes')
('roughly chopped pitted black olives')
('drained jarred capers')
('chopped fresh parsley leaves')
('Parmesan')
('all purpose flour')
('yellow cornmeal')
('sugar')
('baking powder')
('kosher salt')
('egg')
('low fat buttermilk')
('shredded sharp Cheddar')
('canned corn')
('dried chives')
('suggestions: butter and maple syrup')
('white rice')
('butter')
('raisins')
('vanilla extract')
('lemon')
('cinnamon')
('low sodium chicken stock')
('package cheese tortellini')
('package frozen chopped spinach')
('minced garlic')
('basil')
('cheese')
('challah bread')
('chocolate hazelnut spread')
('chopped hazelnuts')
('head escarole')
('can chickpeas')
('red pepper flakes')
('gemelli or fusilli pasta')
('grated parmesan cheese')
('bacon')
('carrot')
('parsley')
('fresh thyme')
('bay leaf')
('heavy cream')
('ground black pepper')
('quinoa')
('long grain rice')
('low sodium chicken broth or water')
('baking soda')
('evaporated milk')
('applesauce')
('brown sugar')
('vegetable oil')
('vanilla')
('creamy unsweetened peanut butter')
('packed brown sugar')
('granulated sugar')
('quick cooking oats')
('candy coated chocolates')
('pancetta')
('eggs')
('freshly grated Parmesan')
('dried penne')
('russet or Yukon gold potatoes')
('kielbasa')
('sweet onion')
('caraway seeds or dill seed')
('salt and freshly ground pepper')
('scallions')
('long grain white rice')
('broccoli florets')
('canola oil')
('finely grated peeled fresh ginger')
('soy sauce')
('honey')
('freshly ground black pepper')
('frozen chicken breasts')
('cornstarch')
('linguine')
('jarred roasted red peppers')
('roasted  almonds')
('seasoned Italian breadcrumbs')
('sherry vinegar')
('granulated garlic')
('smoked sweet paprika')
('basmati rice')
('curry powder')
('vegetable stock')
('cans chickpeas')
('can coconut milk')
('sriracha sauce')
('bread')
('fresh cilantro')
('chopped flat leaf parsley')
('grated Parmigiano-Reggiano')
('can corn kernels')
('tomato paste')
('dried rosemary')
('dried oregano')
('chicken broth')
('can diced tomatoes')
('pasta')
('can white beans')
('can cut green beans')
('bell pepper')
('ketchup')
('dried brown lentils')
('ground beef')
('Worcestershire sauce')
('wheat hamburger buns')
('cheddar cheese')
('pickles and/or pickled jalapeno peppers')
('wheat spaghetti')
('crunchy peanut butter')
('red curry paste')
('rice wine vinegar')
('lime')
('fresh cilantro leaves')
('cucumber')
('pepper flakes or chili paste')
('chipotle in adobo')
('chili powder')
('jars mild salsa')
('cans beans')
('can hominy or corn')
('cider vinegar')
('Suggestions: Tortilla chips and d pickled jalapenos')
('mini marshmallows')
('dark chocolate bars')
('graham crackers')
('cans white meat tuna packed in water')
('minced celery')
('minced red onion')
('minced flat leaf parsley')
('prepared mayonnaise')
('grain mustard')
('squeezed lemon juice')
('bags microwave popcorn')
('seasoning packets from chicken flavored ramen')
('red onion')
('can diced tomatoes with juice')
('chicken stock or white wine')
('assorted olives')
('jar artichoke hearts')
('and freshly ground black pepper')
('jarred pesto')
('fork chunked feta')
('dry toasted pine nuts')
('tahini')
('rice vinegar')
('water')
('spinach')
('sesame oil')
('sesame seeds')
('can San Marzano plum tomatoes')
('instant polenta')
('bunches Swiss chard')
('package farmer cheese')
('cooked black beans')
('lemon juice')
('white wine vinegar')
('ground cumin')
('head iceberg lettuce')
('package frozen artichoke hearts')
('half and half')
('frozen peas')
('finely grated lemon')
('fresh lemon juice')
('refrigerated cheese agnolotti')
('finely grated parmesan cheese')
('torn fresh basil leaves')
('ramen noodles')
('bag frozen stir fry veggie medley')
('creamy peanut butter')
('sweet chili sauce')
('low sodium soy sauce')
('finely chopped green onion')
('shredded rotisserie chicken')
('cooked rice')
('oil')
('old fashioned rolled oats')
('extra crunchy peanut butter')
('raw honey')
('mini chocolate chips')
('dried cranberries')
('sunflower seeds')
('flax seed')
('tomatoes')
('red wine vinegar')
('ginger')
('ground turmeric')
('couscous')
('cilantro')
('mezzi rigatoni')
('shrimp')
('shallot or red onion')
('white wine or low sodium chicken broth')
('can no salt added diced tomatoes')
('torn fresh basil')
('s unsweetened plain soy milk')
('virgin coconut oil')
('syrup')
('packages mushroom ravioli')
('freshly grated nutmeg')
('can corn with red and green peppers')
('can meat only chili')
('can kidney beans')
('can pinto beans')
('can black beans')
('can diced tomatoes with green chiles')
('processed cheese')
('white onion')
('minced peeled ginger')
('bottles root beer')
('apple cider vinegar')
('molasses')
('grainy mustard')
('pinch  red pepper flakes')
('garam masala')
('cans cannellini beans')
('ground turkey breast')
('chipotles in adobo')
('Salt')
('Mexican beer')
('chicken stock')
('can red kidney beans')
('shredded pepper jack cheese')
('cans cannellini or white beans')
('egg yolks')
('grated Parmesan')
('fresh parsley leaves')
('liquor')
('sour')
('sweet')
('enhancer')
('fizzy topper')
('garnish');